services:
  backend:
    build: ./backend
    ports:
      - "3383:3000"
    volumes:
      - "./backend:/usr/src/app"
    depends_on:
      database:
        condition: service_healthy
    networks:
      user-recertification-network:
        ipv4_address: 172.18.0.2

  database:
    build: ./database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: user_rec_db
    ports:
      - "3315:3306"
    networks:
      user-recertification-network:
        ipv4_address: 172.18.0.3
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  user-recertification-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16