CREATE USER 'appUser'@'%' IDENTIFIED BY 'appUser_2024';
GRANT ALL PRIVILEGES ON *.* TO 'appUser'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

-- DROP TABLE IF EXIST users;

/**
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  ad_username VARCHAR(255) NOT NULL UNIQUE,
  email VARCHAR(255) UNIQUE,
  first_name VARCHAR(255),
  last_name VARCHAR(255),
  active BOOLEAN DEFAULT true,
  role VARCHAR(50),
  last_login TIMESTAMP,
  is_deleted BOOLEAN DEFAULT false,
--   permissions JSON,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
**/